sudo: required
services:
  - docker

before_install:
  - docker build -t naveenku/docker-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true naveenku/docker-frontend npm run test   # Test suite exits automatically